# Generated by Django 3.0.8 on 2020-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('whatsapp_link', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('email_link', models.CharField(blank=True, max_length=400)),
                ('footer_details', models.TextField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=500)),
                ('facebook_link', models.CharField(blank=True, max_length=500)),
                ('insta_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
