# Generated by Django 3.0.8 on 2020-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_you', models.CharField(blank=True, max_length=200)),
                ('main_pic', models.ImageField(upload_to='about/%Y/%m/%d/')),
                ('name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='about/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default=1, max_length=200)),
                ('box_name', models.CharField(blank=True, max_length=500)),
                ('box', models.TextField(blank=True)),
                ('design_name', models.CharField(blank=True, max_length=500)),
                ('design', models.TextField(blank=True)),
                ('graphic_name', models.CharField(blank=True, max_length=500)),
                ('graphic', models.TextField(blank=True)),
                ('creative', models.CharField(blank=True, max_length=500)),
                ('creative_detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=500)),
                ('service_description', models.TextField(blank=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
