# Generated by Django 3.0.8 on 2020-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200729_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='design_photo2',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_1',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_2',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_3',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_4',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_5',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_6',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_7',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='final_photo_8',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='product_design_photo',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_main_photo',
            field=models.ImageField(upload_to='port/%Y/%m/%d/'),
        ),
    ]
