# Generated by Django 3.0.8 on 2020-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200729_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='design_photo3',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='design_photo4',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='design_photo5',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='final_photo_10',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='final_photo_9',
            field=models.ImageField(blank=True, upload_to='port/%Y/%m/%d/'),
        ),
    ]
